-- https://github.com/realbxnnie
-- Put in ServerScriptService
-- Script

script.Parent = nil
while true do
	print('COJIqekh	xuiowrhasoyhfwqeudfhurefhaudohvag8ewrhfUIJFTHpuweipgvhauwegfawjue8fgohWAEGIUAEWHRTGAWJRHGJK;W4H5TIPJSENRJYHJW4RHSKLPERTHJW4IOPRHSJOEKRHGSEJKOBRGHASJERGHASWUIOJEFHAWJFBAJKEDFNAWIUEFwjfkgaweklfbawkehbjfawjkhefajefjsdjkgjsdjsioewfjszkdjvskdgjsdlkKJDFKLqwiufhJKXNHKjsdfyiUIWHUFGJKOjidioJWFHUCajkvhaLEFBwjedfgWIUEBGahJWERGBAuefhKEJOFGVBAouhwefhIQWHqiwhuizxhc8Y3R80398609-we8faio4i9ghjDEGHjwfhEFGHpeotEUIFQGJ23HG234YJGHQ78VHE5HT0Q843V7YH9873voeuFPIOWHJGIUW3HT09	7y3P98QU3RIUHSFCJVHSWE8OYTV67QYIVAHWEIPUTHEDSILFU')
end
